### DISCUSSION TITLE
REST catalog with S3T

### DISCUSSION THREAD

**Discussion by gsoundar** [apache/iceberg-rust#1239] [Q&A]
I'm trying to use the REST catalog (https://github.com/apache/iceberg-rust/blob/main/crates/catalog/rest/src/catalog.rs) with S3Tables similar to what is described in https://docs.aws.amazon.com/AmazonS3/latest/userguide/s3-tables-integrating-open-source.html.

The rough snippet of code is:
```
    let mut catalog_props = HashMap::new();
    catalog_props.insert("warehouse".to_string(), TABLE_BUCKET_ARN.to_string());
    catalog_props.insert("rest.sigv4-enabled".to_string(), "true".to_string());
    catalog_props.insert("rest.signing-name".to_string(), "s3tables".to_string());
    catalog_props.insert("rest.signing-region".to_string(), region.to_string());
    let catalog_config = RestCatalogConfig::builder()
        .uri(TABLE_BUCKET_CATALOG.to_string())
        .props(catalog_props)
        .build();
    let catalog = RestCatalog::new(catalog_config);
```

and I get the error
```
Context:
   status: 403 Forbidden
   headers: {"date": "Wed, 23 Apr 2025 19:24:10 GMT", "content-type": "application/json", "content-length": "42", "connection": "keep-alive", "x-amzn-requestid": "XXXXX", "access-control-allow-origin": "*", "x-amzn-errortype": "MissingAuthenticationTokenException", "x-amz-apigw-id": "XXXXX"}
   json: {"message":"Missing Authentication Token"}
```

I think it's because we don't have Sigv4 suppport in the code. Anyone confirm this is the RCA ?
Also does anyone know how Sigv4 support can be plumbed in, maybe through the HttpClient perhaps ?

Thanks!
