### ISSUE TITLE
Make OAuth token server configurable

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg-rust#291]
Java and Python clients support configurable OAuth token server. The Rust client needs that as well.

Here is an pyIceberg configuration example 
```
catalog:
  default:
    uri: http://localhost:8082/
    rest.authorization-url: https://xxx.com/oauth2/token
    credential: client_id:client_secret
```
cc @RussellSpitzer @liurenjie1024 @himadripal
