### ISSUE TITLE
Support customized header in Rest catalog client

### ISSUE THREAD

**Issue by flyrain** [apache/iceberg-rust#292]
Java and Python clients support customized http header. Rust client needs to support that as well.

Here is a Java client configuration example:
```
--conf spark.sql.catalog.rest.header.X-CUSTOMIZED-HEADER=default
```
Here is a Python config example:
```
catalog:
  default:
    uri: http://localhost:8082/
    header.X-CUSTOMIZED-HEADER: default
```

cc @Fokko @RussellSpitzer @liurenjie1024 @himadripal
