### ISSUE TITLE
discussion: refactor docker-compose for tests on macos

### ISSUE THREAD

**Issue by JasonLi-cn** [apache/iceberg-rust#451]
I tried to run `hms_catalog_test` on Mac M1, but the result failed. After checking, I found that the problem was that the host machine could not access the services in the docker container properly. After the following modifications, normal testing can be performed:
The service in the docker container is exposed through port mapping (`port1:port2`), and then `localhost:port1` is used to access the service in the container.

```yaml
version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2024-03-07T00-43-48Z
    ports:
      - "9000:9000" # Port Reflection
    expose:
      - 9000
      - 9001
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_DOMAIN=minio
    command: [ "server", "/data", "--console-address", ":9001" ]

  mc:
    depends_on:
      - minio
    image: minio/mc:RELEASE.2024-03-07T00-31-49Z
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=password
      - AWS_REGION=us-east-1
    entrypoint: >
      /bin/sh -c " until (/usr/bin/mc config host add minio http://minio:9000 admin password) do echo '...waiting...' && sleep 1; done; /usr/bin/mc mb minio/warehouse; /usr/bin/mc policy set public minio/warehouse; tail -f /dev/null "

  hive-metastore:
    image: iceberg-hive-metastore
    platform: linux/amd64
    build: ./
    ports:
      - "9083:9083" # Port Reflection
    expose:
      - 9083
    environment:
      SERVICE_NAME: "metastore"
      SERVICE_OPTS: "-Dmetastore.warehouse.dir=s3a://warehouse/hive/"

```

In addition, is there any other way to help run tests on a Mac?
