### ISSUE TITLE
Encountering `429 Too Many Requests` error every time when accessing Snowflake's Polaris catalog

### ISSUE THREAD

**Issue by Xuanwo** [apache/iceberg-rust#791]
I found iceberg-rust always raise `429 Too Many Requests` while calling Snowflake's Polaris catalog:

```rust
1107=>
Iceberg catalog load failed: ReadTableDataError. Code: 1107, Text = Iceberg catalog load failed: Unexpected => Failed to parse response from rest catalog server!

Context:
   json: 
   code: 429 Too Many Requests

Source: EOF while parsing a value at line 1 column 0
.

<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 
```

**Comment by Xuanwo** [comment]
More detailed error message after test with https://github.com/apache/iceberg-rust/pull/793

```
1107=>
Iceberg catalog load failed: ReadTableDataError. Code: 1107, Text = Iceberg catalog load failed: Unexpected => Failed to parse response from rest catalog server!

Context:
   code: 429 Too Many Requests
   operation: auth
   url: https://xxx.us-east-2.aws.snowflakecomputing.com/polaris/api/catalog/v1/oauth/tokens
   json: 

Source: EOF while parsing a value at line 1 column 0
.

<Backtrace disabled by default. Please use RUST_BACKTRACE=1 to enable> 
```
